### PR TITLE
Configure SSL certs on redeploy

### LINKED ISSUE #334: Incorrect elasticsearch.yml file after deploying more than once (ES cluster goes down)
We have found that if we deploy multiple times the ARM template it could end up with the cluster down because a misconfiguration in the /etc/elastictcsearch.yml file.

It seems that the script elasticsearh-install.sh is not idempotent after configuring https TLS or Transport TLS (mandatory in latest versions). 

Here: https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L646
and here: https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L781
it checks that the certificates files already exists to decide if the functions configure_transport_tls() and configure_http_tls() continues or it returns back.

But, the second time you run this script, these files will already exist and the function will return without adding the configuration needed for Transport TLS and HTTP TLS in the elasticsearch.yml file (it gets written down later in the same function).
As it will switch to the new configuration without this needed parts the cluster will go down after reloading the config  ([this check](https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L1211)  will always be true and will always reload it).

This will happen whenever the customscript will run again. We have observed that this happen any time we change a paramatere of the ARM templates (for example, to add a custom YML configuration, or scale-up the machine, etc..).

### PR DESCRIPTION
**Pull request by russcam**
This commit fixes a bug in elasticsearch-install.sh whereby SSL cert configuration was not added to elasticsearch.yml when a deployment is performed into an existing resource group with an existing deployment.

Fixes #334

### CODE REVIEW

**Comment by russcam** [comment]
Links need to be updated before merging

```sh
npm run links -- --branch master
```

**Comment by russcam** [comment]
merging this in

**Comment by Mpdreamz** [comment]
Sorry for the delay in review, should have commented. 

I wanted to pull this down to understand the fix as this PR seemed to do more then expected from what I can tell scanning the PR on my phone which is not very effective for comprehension on my end :)

Let's discuss this on our sync in a bit.

**Comment by russcam** [comment]
GitHub's diff is not very good at showing what the change is 😃 It simply moves the cert generation processes into an `else` branch that runs when no certs exist on disk, but allows all branches to flow to the proceeding commands that write certificate related configuration to elasticsearch.yml. Previously, the bug was that

1. when certs didn't exist on disk (i.e. initial deployment), the proceeding commands to write certificate related configuration to elasticsearch.yml ran, 

but

2. when certs did exist on disk (i.e. a redeployment), the function exited early _without_ running the proceeding commands to write certificate related configuration to elasticsearch.yml

**Pull request merged**
