### PR TITLE
Update 7.6 version to latest patch, 7.6.2

### PR DESCRIPTION
**Pull request by quimrodri**
Hi all!

With these update I'm trying to update to latest 7.6 patch version, 7.6.2. We are deploying ElasticSearch 7.6.0 using this ARM template and found some nasty bugs solved in the latest patch version. 

I don't know to where I should point the links with "npm run links". Should I point them to my cloned repo? To the original one but the branch? If you let me know the correct approach I can update the PR adding this change.

Let me know if missed something 🙈

### CODE REVIEW

**Comment by russcam** [comment]
The changes look OK @quimrodri. Would you be able to [sign the CLA please](https://www.elastic.co/contributor-agreement), so that we can accept the PR?

**Comment by quimrodri** [comment]
Hi @russcam I've tried several time to do sign it (I've like 5 or 6 signed documents). I don't know how this signed document gets linked back to this PR. I'm just expecting that once I have signed it it just will work out by itself without any manual action from my side.

Maybe I need to recreate the PR again?

**Comment by quimrodri** [comment]
Hi @russcam, just in case it was not clear from my previous comment: I already signed the CLA and you can merge the PR whenever you please.

Thanks!

**Comment by russcam** [comment]
ported to `7.6` branch

**Pull request merged**
