### PR TITLE
Escape double quotes in passwords and use kibana keystore

### PR DESCRIPTION
**Pull request by russcam**
This PR fixes a bug when a user supplied password for a built-in user account contains one or more double quotes. Since the password is inserted into a JSON string that forms part of a JSON object for the update password API request body, any double quotes need to be escaped within the password to form valid JSON.

When a request to update a built-in user password fails, the deployment should fail, but this was not happening because the status code of the function performing the operation was not propagated correctly. This is also addressed.

In addition to this bug fix, this PR also 

- creates and uses the kibana keystore to store credentials for Kibana
- uses `kibana_system` for the built-in Kibana user in 7.8.0+

### CODE REVIEW

**Comment by russcam** [comment]
run 

```
npm run links -- --branch master
```

before merging

**Comment by russcam** [comment]
Tested with 6.8.11, 7.8.1 and 7.9.0 with passwords containing `` ` ``,  `:`, `'`, `"`, `$`, `${foo}`, `^`, and `~`

**Review by Mpdreamz — COMMENTED** [review]
`"` strikes again 💥

**Comment by russcam** [comment]
@Mpdreamz Between the single quote escaping in [ubuntuSettings.json](https://github.com/elastic/azure-marketplace/blob/master/src/settings/ubuntuSettings.json) and this, there's a lot of contexts to escape 😄 

The move to using kibana keystore is needed, not only because it is better than storing credentials in kibana.yml, but also because it is not possible to escape environment variable interpolation in kibana.yml, which could cause passwords containing `${ }` to be interpolated and error on Kibana startup. I opened https://github.com/elastic/kibana/issues/75515 to discuss.

**Pull request merged**
