### PR TITLE
fix resourceId issues found by TTK

### PR DESCRIPTION
**Pull request by bmoore-msft**
In an email conversation w/ @russcam we discussed fixing some best practice issues found by the TTK for marketplace cert.  This PR addresses some low hanging fruit.

### CODE REVIEW

**Comment by russcam** [comment]
Thanks for opening @bmoore-msft! I've run our integration tests and all looks good to me. Would you be able to [sign the CLA](https://www.elastic.co/contributor-agreement) so that I can pull the change in?

**Review by russcam — APPROVED** [review]

**Comment by bmoore-msft** [comment]
I haven't forgotten... still trying to get our OSS folks to give me permission to sign the CLA...

**Comment by russcam** [comment]
Hi @bmoore-msft, have you heard anything from the Microsoft OSS folks?

**Comment by bmoore-msft** [comment]
Sigh... no.  There is a tool that I have to go through (at least that's what they are telling me) and the tool does not work.

**Comment by russcam** [comment]
Thanks again for this PR, @bmoore-msft 👍

**Comment by bmoore-msft** [comment]
I hope we got all of them... ;)

**Comment by russcam** [comment]
I have full confidence we'll find out if we haven't 😆

**Comment by bmoore-msft** [comment]
... or the TTK wouldn't be doing it's job

**Pull request merged**
