### PR TITLE
Standard_A* VMs moved to v2

### PR DESCRIPTION
**Pull request by dwaynebailey**
The VMs like Standard_A2 have been discontinued and now are listed as
Standard_A2_v2

Creating this as Draft as I'm not 100% sure about the changes I've made in areas where there are coded disk/memory/CPU sizes.

### CODE REVIEW

**Comment by russcam** [comment]
Thanks for opening @dwaynebailey. It looks like [A-series is superseded by Av2-series as you indicate](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-previous-gen#a-series). 

I would be OK with dropping support for the A-series and adding the Av2-series. This might also be a good opportunity to remove support for the D-series, DS-series, F-series, Fs-series and Ls-series.

**Comment by Mpdreamz** [comment]
Is there such as thing as `Standard_A3_v2` ? The documentation on vm sizes does not list it. 

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#av2-series

Thanks for opening the PR @dwaynebailey be good to do another passover all VM sizes as @russcam although that's something we can pick up perhaps

**Comment by michaelschmit** [comment]
Along these same lines, I have been receiving the following error when deploying recently:

We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance

This is for the data nodes since I think the Standard_D1 is becoming obsolete.  The default should probably get switched over to Standard_D1_v2.

**Comment by michaelschmit** [comment]
Along these same lines, I have been receiving the following error when deploying recently:

We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance

This is for the data nodes since I think the Standard_D1 is becoming obsolete.  The default should probably get switched over to Standard_D1_v2.

**Comment by russcam** [comment]
Closing this in favour of #324, which updates the default VM SKUs to newer options.

**Pull request closed without merging**
