### PR TITLE
Option to install additional plugins

### PR DESCRIPTION
**Pull request by ajhewett**
Add an option to install additional plugins (e.g. delete-by-query or kopf).
By default no additional plugins are installed.

Additional plugins can be installed using the `esAdditionalPlugins` parameter.  Multiple plugins are separated by a semicolon.  e.g. to install `delete-by-query` and `kopf` use a parameter value like
    `"esAdditionalPlugins": { "value": "delete-by-query;lmenezes/elasticsearch-kopf/2.0" }`

### CODE REVIEW

**Comment by ajhewett** [comment]
BTW I am new to git and pull requests so would welcome any advice.

**Comment by Mpdreamz** [comment]
:heart: this so much!

quick look over on phone yields nothing obvious. Will do a more extensive review next week. 

Thank you @ajhewett :+1:

**Comment by russcam** [comment]
@ajhewett Thanks for submitting 👍  

Would love to get this into the next version of the template; the template has been refactored quite a bit since this PR was created so would you be able to rebase this PR against latest on master?

**Comment by ajhewett** [comment]
Rebased to elastic:master
Added the new parameter to createUiDefinition.json and README.md

**Comment by russcam** [comment]
@ajhewett sorry to be a pain, but would you be able to rebase against `master` and squash all of the commits into one (using [`git rebase -i`](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history)) and update the PR with the single commit (you'll need to `git push -f` to do this)?

**Comment by ajhewett** [comment]
As a git noob I have managed to trash my additional-plugins branch.
Eventually it was simpler to create a new branch and redo the changes.
Will submit a new pull request.

**Pull request closed without merging**
